name: chronyfit
description: chrono App.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Icônes
  cupertino_icons: ^1.0.8

  # Packages
  provider: ^6.0.0
  shared_preferences: ^2.2.0
  file_picker: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Configuration des Shaders
  shaders:
    - shaders/background.frag