name: chronyfit
description: Chrono App.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Icônes
  cupertino_icons: ^1.0.8

  # Packages
  provider: ^6.1.2
  shared_preferences: ^2.2.0
  file_picker: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # Configuration des Shaders
  shaders:
    - shaders/background.frag
    - shaders/run_background.frag

# Configuration des icônes
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/ChronyFit_iCO.png"
  min_sdk_android: 21 # Correction ici : le commentaire se fait avec #